# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ARM_CLIENT_ID: $(servicePrincipalId) 
  ARM_CLIENT_SECRET: $(servicePrincipalKey) 
  ARM_SUBSCRIPTION_ID: $(subscriptionId) 
  ARM_TENANT_ID: $(tenantId)


stages:
- stage: plan
  displayName: "Terraform Plan for AutoScale VMs"
  jobs:
  - job: Terraformjob
    displayName: "Terraform Run"
    steps:
    - task: AzureCLI@2
      inputs:
        #azureSubscription: $(azureServiceConnection)
        scriptType: bash
        inlineScript: |
         terraform init
         terraform validate
         terraform plan